### ISSUE TITLE
As a developer, I can use a CI

### ISSUE THREAD

**Issue by benox3** [getvinch/vinch#5]
### Technical Requirements

- [x] Set up [Travis CI](https://travis-ci.org/)
- [x] Run lint, test, and build on branch/PR
- [x] Set up [Coveralls](https://coveralls.io/)
- [x] Run deploy to Netlify on merge to `master`

Depends on #4, #6

**Comment by remarkablemark** [comment]
https://travis-ci.org/getvinch/vinch

**Comment by remarkablemark** [comment]
https://coveralls.io/github/getvinch/vinch
